version = 0.1

[default.global.parameters]
stack_name = "stack-ticket-bot"
region = "ap-northeast-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
template_file = "c:\\Users\\step6\\Documents\\repos\\github\\ticket-bot-backend\\lambda-python3.13\\template.yaml"
dependency_layer = false

  [default.sync.parameters.parameter_overrides]
TicketLineChannelID = "2007876157"
TicketLineChannelSecret = "9b6e53067a1a1d2810c23b184bfdfdc6"

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
